name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.6", "2.7", "3.0", "3.1"]
        gemfile: ["rails_6_0", "rails_6_1", "rails_7_0"]
        exclude:
          - ruby-version: "2.6"
            gemfile: "rails_7_0"
          - ruby-version: "3.1"
            gemfile: "rails_6_0"
          - ruby-version: "3.1"
            gemfile: "rails_6_1"
      fail-fast: false

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    services:
      postgres:
        image: postgis/postgis
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: spatial_features_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      # libgeos and gdal are required and must be installed before `bundle install`
      # NB: if you add libs here that are required for Gem native extensions be sure to clear the
      # bundle cache in `ruby/setup-ruby` so that the gems are re-compiled
      - name: Install GEOS
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install libpq-dev libgeos-dev libgeos3.10.2 libproj-dev gdal-bin -y

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 4

      - name: Run tests
        run: bundle exec rspec
